const X_AXIS = 'ABCDEFGHI'
const Y_AXIS = '0123456789'

const BLACK = "BLACK"
const RED = "RED"

const ROOK = "ROOK"
const PAWN = "PAWN"
const BISHOP = "BISHOP"
const GUARD = "GUARD"
const KING = "KING"
const CANNON = "CANNON"
const KNIGHT = "KNIGHT"

const BLACK_ROOK = BLACK+"_"+ROOK
const BLACK_PAWN = BLACK+"_"+PAWN
const BLACK_BISHOP = BLACK+"_"+BISHOP
const BLACK_GUARD = BLACK+"_"+GUARD
const BLACK_KING = BLACK+"_"+KING
const BLACK_CANNON = BLACK+"_"+CANNON
const BLACK_KNIGHT = BLACK+"_"+KNIGHT

const RED_ROOK = RED+"_"+ROOK
const RED_PAWN = RED+"_"+PAWN
const RED_BISHOP = RED+"_"+BISHOP
const RED_GUARD = RED+"_"+GUARD
const RED_KING = RED+"_"+KING
const RED_CANNON = RED+"_"+CANNON
const RED_KNIGHT = RED+"_"+KNIGHT

module.exports = {
  X_AXIS, Y_AXIS,
  BLACK, RED,
  ROOK, BLACK_ROOK, RED_ROOK,
  PAWN, BLACK_PAWN, RED_PAWN,
  BISHOP, BLACK_BISHOP, RED_BISHOP,
  GUARD, BLACK_GUARD, RED_GUARD,
  KING, BLACK_KING, RED_KING,
  CANNON, BLACK_CANNON, RED_CANNON,
  KNIGHT, BLACK_KNIGHT, RED_KNIGHT,
}