const X_AXIS = 'ABCDEFGHI'
const Y_AXIS = '0123456789'

const BLACK_KING_ZONE = [
  'D7', 'E7', 'F7',
  'D8', 'E8', 'F8',
  'D9', 'E9', 'F9',
]

const RED_KING_ZONE = [
  'D0', 'E0', 'F0',
  'D1', 'E1', 'F1',
  'D2', 'E2', 'F2',
]

const RED_RIVER_BORDER_Y = 4
const BLACK_RIVER_BORDER_Y = 5

const BLACK = "BLACK"
const RED = "RED"

const ROOK = "ROOK"
const PAWN = "PAWN"
const BISHOP = "BISHOP"
const GUARD = "GUARD"
const KING = "KING"
const CANNON = "CANNON"
const KNIGHT = "KNIGHT"

const BLACK_ROOK = BLACK+"_"+ROOK
const BLACK_PAWN = BLACK+"_"+PAWN
const BLACK_BISHOP = BLACK+"_"+BISHOP
const BLACK_GUARD = BLACK+"_"+GUARD
const BLACK_KING = BLACK+"_"+KING
const BLACK_CANNON = BLACK+"_"+CANNON
const BLACK_KNIGHT = BLACK+"_"+KNIGHT

const RED_ROOK = RED+"_"+ROOK
const RED_PAWN = RED+"_"+PAWN
const RED_BISHOP = RED+"_"+BISHOP
const RED_GUARD = RED+"_"+GUARD
const RED_KING = RED+"_"+KING
const RED_CANNON = RED+"_"+CANNON
const RED_KNIGHT = RED+"_"+KNIGHT

const BLACK_TROOPS_MAP = {
  A9: BLACK_ROOK, B9: BLACK_KNIGHT, C9: BLACK_BISHOP, D9: BLACK_GUARD, E9: BLACK_KING, F9: BLACK_GUARD, G9: BLACK_BISHOP, H9: BLACK_KNIGHT, I9: BLACK_ROOK,
  B7: BLACK_CANNON, H7: BLACK_CANNON,
  A6: BLACK_PAWN, C6: BLACK_PAWN, E6: BLACK_PAWN, G6: BLACK_PAWN, I6: BLACK_PAWN
}
const RED_TROOPS_MAP = {
  A0: RED_ROOK, B0: RED_KNIGHT, C0: RED_BISHOP, D0: RED_GUARD, E0: RED_KING, F0: RED_GUARD, G0: RED_BISHOP, H0: RED_KNIGHT, I0: RED_ROOK,
  B2: RED_CANNON, H2: RED_CANNON,
  A3: RED_PAWN, C3: RED_PAWN, E3: RED_PAWN, G3: RED_PAWN, I3: RED_PAWN
}

const SYMBOLS = {
  BLACK_BISHOP: 'b', RED_BISHOP: 'B',
  BLACK_CANNON: 'c', RED_CANNON: 'C',
  BLACK_GUARD:  'g', RED_GUARD:  'G',
  BLACK_KING:   'k', RED_KING:   'K', 
  BLACK_KNIGHT: 'n', RED_KNIGHT: 'N',
  BLACK_PAWN:   'p', RED_PAWN:   'P',
  BLACK_ROOK:   'r', RED_ROOK:   'R',
}

const swapKeyValue = (json) => {
  let ret = {};

  for(let key in json) {
    ret[json[key]] = key;
  }

  return ret;
}

const SYMBOLS_REVERSE = swapKeyValue(SYMBOLS)

module.exports = {
  X_AXIS, Y_AXIS,
  BLACK, RED,
  ROOK, BLACK_ROOK, RED_ROOK,
  PAWN, BLACK_PAWN, RED_PAWN,
  BISHOP, BLACK_BISHOP, RED_BISHOP,
  GUARD, BLACK_GUARD, RED_GUARD,
  KING, BLACK_KING, RED_KING,
  CANNON, BLACK_CANNON, RED_CANNON,
  KNIGHT, BLACK_KNIGHT, RED_KNIGHT,
  BLACK_TROOPS_MAP,
  RED_TROOPS_MAP,
  SYMBOLS, SYMBOLS_REVERSE,
  BLACK_KING_ZONE, RED_KING_ZONE,
  RED_RIVER_BORDER_Y, BLACK_RIVER_BORDER_Y,
}